### ISSUE TITLE
Add readme for flagd provider

### ISSUE THREAD

**Issue by agardnerIT** [open-feature/python-sdk-contrib#14]
https://github.com/open-feature/python-sdk-contrib/tree/main/open_feature_contrib/providers/flagd

It would be great to have a readme with some sample snippets of how to use the flagd Python provider.

@tcarrio tagging you as the last person to touch the flagd provider (and thus probably most likely to be the expert).

**Comment by federicobond** [comment]
We just released [openfeature-provider-flagd](https://github.com/open-feature/python-sdk) with a relatively spartan but usable README.
