### ISSUE TITLE
[flagd-RPC] TLS custom cert support

### ISSUE THREAD

**Issue by toddbaert** [open-feature/python-sdk-contrib#54]
Support custom certs for RPC flagd connection.

- [ ] author can specify a custom cert for TLS
- [ ] not compatible with unix sockets (see: https://github.com/open-feature/python-sdk-contrib/issues/12)

**Comment by aepfli** [comment]
with the newest addition to our flagd-testbed (submodule test-harness in here) - there is now also a ssl image with a custom cert. which you can use
