### ISSUE TITLE
Automate release process

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/python-sdk-contrib#6]

**Comment by psolarcz** [comment]
@beeme1mr I can take this issue, just let me know the steps.

**Comment by beeme1mr** [comment]
Hey @psolarcz, we use [Release Please](https://github.com/googleapis/release-please) for automating releases in other repos. We'll just need to replicate what we did in the [Python SDK](https://github.com/open-feature/python-sdk/blob/main/release-please-config.json) but configure it to work in a monorepo.

**Comment by federicobond** [comment]
Before moving forward we should decide if we will publish everything as a single package or if we split it into multiple packages.

FWIW, I think it's ok to release a single contrib package now and eventually split it up once it accumulates too much code.

**Comment by beeme1mr** [comment]
It would be great to split it into multiple packages if possible. I can help from a Release Please perspective.

**Comment by federicobond** [comment]
Split done in https://github.com/open-feature/python-sdk-contrib/pull/35, we are ready to configure Release Please now.

**Comment by beeme1mr** [comment]
Okay, I'll give it a shot.
